name: microbellm
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas>=2.0.0
  - numpy>=1.24.0
  - pip
  - pip:
    - pandas
    - Flask
    - flask-socketio
    - requests
    - colorama
    - tqdm
    - gunicorn
    - eventlet
    - tenacity 
